/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 lemon-bath-tub.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lemon-bath-tub.glb')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes['lemon-bath-tub'].geometry} material={materials['whale-bath-tub-color']} position={[-10.089, 3.919, -41.458]} rotation={[0, -1.565, 0]} scale={[3.318, 0.371, 3.318]} material-color="green"/> 
      <mesh geometry={nodes['tap-opener'].geometry} material={materials['tap-material']} position={[-15.491, 5.002, -41.415]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={0.131} />
      <mesh geometry={nodes['tap-head'].geometry} material={materials['tap-material']} position={[-14.477, 4.503, -41.466]} rotation={[-Math.PI, 1.539, -Math.PI]} scale={[0.571, 0.208, 0.571]} />
    </group>
  )
}

useGLTF.preload('/lemon-bath-tub.glb')
