/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 shoe.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shoe(props) {
  const { nodes, materials } = useGLTF('/shoe.gltf')
  return (
    <group {...props} dispose={null} scale={1.2}>
      <mesh geometry={nodes.shoe.geometry} material={materials.laces} material-color="grey"/>
      <mesh geometry={nodes.shoe_1.geometry} material={materials.mesh} material-color="white"/>
      <mesh geometry={nodes.shoe_2.geometry} material={materials.caps} material-color="blue"/>
      <mesh geometry={nodes.shoe_3.geometry} material={materials.inner} material-color="blue"/>
      <mesh geometry={nodes.shoe_4.geometry} material={materials.sole} material-color="gold"/>
      <mesh geometry={nodes.shoe_5.geometry} material={materials.stripes} material-color="black"/>
      <mesh geometry={nodes.shoe_6.geometry} material={materials.band} material-color="black"/>
      <mesh geometry={nodes.shoe_7.geometry} material={materials.patch} material-color="black"/>
    </group>
  )
}

useGLTF.preload('/shoe.gltf')
